### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by SebastianGiro** [GatoLoko/Wattpad2Epub#9]
It would be nice if we had a better documentation with:

1) How to install
2) How to run
3) Where the file output will be

**Comment by GatoLoko** [comment]
I didn't write any documentation because I though it was straightforward:

1. It's not installable, just git clone it into a directory of your choice
2. Like any other python script. It even has instructions when you run it without any parameters.
3. In the current working directory.

Do you have any suggestion on how to document that?
